### ISSUE TITLE
Release injected object resource on scope exit

### ISSUE THREAD

**Issue by koi8-r** [alecthomas/injector#119]
I want to inject a database connection during processing of http request in the custom request scope. Where i can close the connection after request is processed and request scope exits. Can i do this? And can i use custom scope for this?

**Comment by jstasiak** [comment]
You can close the connection explicitly after you're done using it. Or instead of opening/allocating a connection right away you can inject a context manager that lets you manage the connection. Or you can provide an after-request hook that requests the connection object and closes it there. Possibly other ways too, totally up to your code.

Yes, you could (ab)use a custom scope for this – see https://github.com/alecthomas/flask_injector/blob/18282a42539c8a8809feff1f466f763116e10bda/flask_injector.py (look for `clenaup`) and, quite related, https://github.com/alecthomas/flask_injector/issues/37.

**Comment by koi8-r** [comment]
Exactly what is needed. Thanks a lot for the examples.
