### ISSUE TITLE
"from injector import Key" fails

### ISSUE THREAD

**Issue by garyrob** [alecthomas/injector#144]
The Keys section on the Terminology page contains the line:

`from injector import Key`

However, when I run that line in the terminal, I get an error: "ImportError: cannot import name 'Key' from 'injector'". Other imports such as

`from injector import InstanceProvider`

work fine in my setup.

**Comment by gimbo** [comment]
Looking at the [Changelog](https://injector.readthedocs.io/en/latest/changelog.html), we have:

> 0.17.0 — Deprecated `Key`, `SequenceKey` and `MappingKey` – use real types or type aliases instead

and

> 0.18.0  — Removed previously deprecated `Key`, `BindingKey`, `SequenceKey` and `MappingKey` pseudo-types

[Here's the commit where they were deprecated](https://github.com/alecthomas/injector/commit/0b1fcd56a7240a4797b33e1c4185017e6d949dd3). And [here's a commit](https://github.com/alecthomas/injector/commit/a84d4c84e31956c958af41adf3885524d2be2195) where the `README` was updated.

So the advice is apparently to "use real types or type aliases instead".  E.g perhaps something like this would suffice for the example on the Terminology page...?

```
from typing import NewType

Name = NewType('Name', int)
Description = NewType('Description', int)
```

?

I'm guessing (as a beginner trying to comprehend things) that since the key classes aren't ever instantiated (?) it doesn't matter what type we base our new type off? So I went for `int` here.

I'm hesitant about that conclusion however, as in that README-update commit, @jstasiak replaced

```
Configuration = Key('configuration')
```

with a real `Configuration` class, carrying some data  — so maybe the deprecation of `Key` carries more semantic weight than I'm understanding here. But as I said, I'm new here so I don't really know, just trying to figure it out too. :-)

**Comment by passjwhub** [comment]
I think nobody to update the docs  - _ - !

**Comment by jstasiak** [comment]
Thanks for the info, documentation updated in e686f36d88a6fe1f67a8aeff2d07238616082b3e.

@gimbo Anything returned when you requested a `Key` instance before wasn't type-checked as the types were opaque to type checkers, there was no way to specify the return type of `Injector.get()` etc.. Now, since `Key` and family have been removed and `NewType` support has been added to replace `Key`, the types do matter – if you have

```
UserId = NewType('UserId', int)
```

and then try to do string-things with it

```
def __init__(self, user_id: UserId):
    user_id + ' something'
```

mypy will complain (and so should other type checkers).
