### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by richburdon** [alecthomas/injector#51]
When something isn't bound the following exception is thrown in BaseKey:

    raise Exception('Instantiation of %s prohibited ...)

I think this is run in a different Thread, so in my case, the main Flask app isn't able to catch it, so I have no indication (other than logs) that an error has occurred (esp. since injector is lazy -- with no eager option -- so bindings happen after the server has started).

Is there a workaround?

**Comment by alecthomas** [comment]
I would suggest that swallowing all exceptions is a limitation of Flask, not an issue in injector...

**Comment by alecthomas** [comment]
Or perhaps Flask can be configured with a [custom error handler](http://flask.pocoo.org/docs/0.10/patterns/apierrors/)?

**Comment by jstasiak** [comment]
@richburdon I recommend any even remotely serious application (by serious I mean one that you rely on) should log failures in a way that makes them visible to the developer (whether it's Sentry /I can recommend this one/, syslog + some filters + dashboard or any other solution).

The nature of this library is that you can always get an exception at runtime - in general it's good to anticipate that because whether it's an error caused by failed injection or any other factor (unreachable external service, no disk space etc.) you probably want to know about it as soon as it happens.
